In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split , KFold
%matplotlib inline

In [2]:
import statistics as stats

In [3]:
df = pd.read_csv('data/data.csv')
df.head()

_id  ccf  age  sex  pain location  pain w exertion  relieved after rest  \
0  1254    0   40    1              1                0                  0.0   
1  1255    0   49    0              1                0                  0.0   
2  1256    0   37    1              1                0                  0.0   
3  1257    0   48    0              1                1                  1.0   
4  1258    0   54    1              1                0                  1.0   

   pncaden  chest pain type  resting bp s  ...  rcaprox  rcadist  dummy 7  \
0      NaN                2         140.0  ...      NaN      NaN      1.0   
1      NaN                3         160.0  ...      NaN      NaN      1.0   
2      NaN                2         130.0  ...      NaN      NaN      1.0   
3      NaN                4         138.0  ...      2.0      NaN      1.0   
4      NaN                3         150.0  ...      1.0      NaN      1.0   

   dummy 8  dummy 9  dummy 10  dummy 11  dummy 12  dummy 13  dummy 14  
0      1.0      1.0       1.0       1.0       NaN       NaN      name  
1      1.0      1.0       1.0       1.0       NaN       NaN      name  
2      1.0      1.0       1.0       1.0       NaN       NaN      name  
3      1.0      1.0       1.0       1.0       NaN       NaN      name  
4      1.0      1.0       1.0       1.0       NaN       NaN      name  

[5 rows x 76 columns]

In [4]:
df.shape

(617, 76)

In [5]:
pd.__version__

'1.0.5'

In [6]:
df.columns

Index(['_id', 'ccf', 'age', 'sex', 'pain location', 'pain w exertion',
       'relieved after rest', 'pncaden', 'chest pain type', 'resting bp s',
       'hypertension', 'cholesterol', 'smoker', 'cigarettes per day',
       'years of smoking', 'fasting blood sugar', 'diabetes', 'family hist',
       'resting ecg', 'ekg month', 'ekg day', 'ekg yr', 'digitalis',
       'beta blocker', 'nitrates', 'calcium channel blocker', 'diuretic',
       'exercise protocol', 'duration of exercise', 'thaltime',
       'mets achieved', 'max heart rate', 'resting heart rate',
       'peak exercise bp 1', 'peak exercise bp 2', 'dummy 1', 'resting bp d',
       'exercise angina', 'xhypo', 'oldpeak', 'ST slope', 'ST height at rest',
       'ST heaight at peak', 'flouroscopy', 'dummy 2', 'dummy 3',
       'resting ejection fraction', 'rest wall motion abnormality',
       'exercise ejection fraction', 'exercsie wall motion', 'thal', 'dummy 4',
       'dummy 5', 'dummy 6', 'cath month', 'cath day', 'cath yr'

In [7]:
# Using useful features
df = df.drop(['dummy 1' , 'dummy 2','dummy 3','dummy 4','dummy 5','dummy 6','dummy 7','dummy 8','dummy 9','dummy 10',\
             'dummy 11','dummy 12','dummy 13','dummy 14'] , axis = 1)
df.shape

(617, 62)

In [8]:
df.columns

Index(['_id', 'ccf', 'age', 'sex', 'pain location', 'pain w exertion',
       'relieved after rest', 'pncaden', 'chest pain type', 'resting bp s',
       'hypertension', 'cholesterol', 'smoker', 'cigarettes per day',
       'years of smoking', 'fasting blood sugar', 'diabetes', 'family hist',
       'resting ecg', 'ekg month', 'ekg day', 'ekg yr', 'digitalis',
       'beta blocker', 'nitrates', 'calcium channel blocker', 'diuretic',
       'exercise protocol', 'duration of exercise', 'thaltime',
       'mets achieved', 'max heart rate', 'resting heart rate',
       'peak exercise bp 1', 'peak exercise bp 2', 'resting bp d',
       'exercise angina', 'xhypo', 'oldpeak', 'ST slope', 'ST height at rest',
       'ST heaight at peak', 'flouroscopy', 'resting ejection fraction',
       'rest wall motion abnormality', 'exercise ejection fraction',
       'exercsie wall motion', 'thal', 'cath month', 'cath day', 'cath yr',
       'target', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain', 'ramus'

In [9]:
null = {}
for i in range(df.shape[1]):
    null[i]= df.iloc[:,i].isnull().sum()
null

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 4,
 7: 617,
 8: 0,
 9: 59,
 10: 34,
 11: 30,
 12: 387,
 13: 415,
 14: 427,
 15: 90,
 16: 545,
 17: 422,
 18: 2,
 19: 53,
 20: 54,
 21: 53,
 22: 66,
 23: 64,
 24: 63,
 25: 61,
 26: 80,
 27: 112,
 28: 56,
 29: 384,
 30: 105,
 31: 55,
 32: 56,
 33: 63,
 34: 63,
 35: 59,
 36: 55,
 37: 58,
 38: 62,
 39: 308,
 40: 143,
 41: 142,
 42: 606,
 43: 589,
 44: 587,
 45: 615,
 46: 612,
 47: 475,
 48: 11,
 49: 9,
 50: 9,
 51: 0,
 52: 275,
 53: 236,
 54: 246,
 55: 276,
 56: 235,
 57: 285,
 58: 271,
 59: 290,
 60: 245,
 61: 270}

In [10]:
keys = []
null_keys = list(null.keys())
null_values = list(null.values())
for i in range(62):
    if null_values[i] > df.shape[0]/2:
        keys.append(null_keys[i])
    else:
        continue
keys

[7, 12, 13, 14, 16, 17, 29, 42, 43, 44, 45, 46, 47]

In [11]:
df.drop(df.columns[keys] , axis = 1 , inplace = True)
df.shape

(617, 49)

In [12]:
null = {}
for i in range(df.shape[1]):
    null[i]= df.iloc[:,i].isnull().sum()
null

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 4,
 7: 0,
 8: 59,
 9: 34,
 10: 30,
 11: 90,
 12: 2,
 13: 53,
 14: 54,
 15: 53,
 16: 66,
 17: 64,
 18: 63,
 19: 61,
 20: 80,
 21: 112,
 22: 56,
 23: 105,
 24: 55,
 25: 56,
 26: 63,
 27: 63,
 28: 59,
 29: 55,
 30: 58,
 31: 62,
 32: 308,
 33: 143,
 34: 142,
 35: 11,
 36: 9,
 37: 9,
 38: 0,
 39: 275,
 40: 236,
 41: 246,
 42: 276,
 43: 235,
 44: 285,
 45: 271,
 46: 290,
 47: 245,
 48: 270}

In [13]:
df.columns

Index(['_id', 'ccf', 'age', 'sex', 'pain location', 'pain w exertion',
       'relieved after rest', 'chest pain type', 'resting bp s',
       'hypertension', 'cholesterol', 'fasting blood sugar', 'resting ecg',
       'ekg month', 'ekg day', 'ekg yr', 'digitalis', 'beta blocker',
       'nitrates', 'calcium channel blocker', 'diuretic', 'exercise protocol',
       'duration of exercise', 'mets achieved', 'max heart rate',
       'resting heart rate', 'peak exercise bp 1', 'peak exercise bp 2',
       'resting bp d', 'exercise angina', 'xhypo', 'oldpeak', 'ST slope',
       'ST height at rest', 'ST heaight at peak', 'cath month', 'cath day',
       'cath yr', 'target', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain',
       'ramus', 'om1', 'om2', 'rcaprox', 'rcadist'],
      dtype='object')

In [14]:
keys = []
null_keys = list(null.keys())
null_values = list(null.values())
for i in range(49):
    if null_values[i] >= 200:
        keys.append(null_keys[i])
    else:
        continue
keys

[32, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]

In [15]:
df.drop(df.columns[keys] , axis = 1 , inplace = True)

In [16]:
df.shape

(617, 38)

In [17]:
null = {}
for i in range(df.shape[1]):
    null[i]= df.iloc[:,i].isnull().sum()
null

{0: 0,
 1: 0,
 2: 0,
 3: 0,
 4: 0,
 5: 0,
 6: 4,
 7: 0,
 8: 59,
 9: 34,
 10: 30,
 11: 90,
 12: 2,
 13: 53,
 14: 54,
 15: 53,
 16: 66,
 17: 64,
 18: 63,
 19: 61,
 20: 80,
 21: 112,
 22: 56,
 23: 105,
 24: 55,
 25: 56,
 26: 63,
 27: 63,
 28: 59,
 29: 55,
 30: 58,
 31: 62,
 32: 143,
 33: 142,
 34: 11,
 35: 9,
 36: 9,
 37: 0}

In [18]:
df.columns

Index(['_id', 'ccf', 'age', 'sex', 'pain location', 'pain w exertion',
       'relieved after rest', 'chest pain type', 'resting bp s',
       'hypertension', 'cholesterol', 'fasting blood sugar', 'resting ecg',
       'ekg month', 'ekg day', 'ekg yr', 'digitalis', 'beta blocker',
       'nitrates', 'calcium channel blocker', 'diuretic', 'exercise protocol',
       'duration of exercise', 'mets achieved', 'max heart rate',
       'resting heart rate', 'peak exercise bp 1', 'peak exercise bp 2',
       'resting bp d', 'exercise angina', 'xhypo', 'oldpeak',
       'ST height at rest', 'ST heaight at peak', 'cath month', 'cath day',
       'cath yr', 'target'],
      dtype='object')

# Filling null values

## 1. 'Relieved after rest'

In [19]:
df.columns[6] , df[df.columns[6]].unique()

('relieved after rest', array([ 0.,  1., nan]))

In [20]:
df[df.columns[6]].fillna(stats.mode(df[df.columns[6]]) , inplace = True)

In [21]:
df.columns[6] , df[df.columns[6]].unique() , df[df.columns[6]].value_counts()

('relieved after rest',
 array([0., 1.]),
 1.0    416
 0.0    201
 Name: relieved after rest, dtype: int64)

## 2. 'resting bp s'

In [22]:
df.columns[8]

'resting bp s'

In [23]:
df[df.columns[8]]

0      140.0
1      160.0
2      130.0
3      138.0
4      150.0
       ...  
612    127.0
613      NaN
614    122.0
615      NaN
616    120.0
Name: resting bp s, Length: 617, dtype: float64

In [24]:
df[df.columns[8]].fillna(df[df.columns[8]].mean() , inplace = True)

## 3. 'hypertension'

In [25]:
df.columns[9]

'hypertension'

In [26]:
df[df.columns[9]]

0      0.0
1      1.0
2      0.0
3      0.0
4      0.0
      ... 
612    0.0
613    0.0
614    1.0
615    0.0
616    1.0
Name: hypertension, Length: 617, dtype: float64

In [27]:
df[df.columns[9]].fillna(stats.mode(df[df.columns[9]]) , inplace = True)

In [28]:
df.columns[9] , df[df.columns[9]].unique() , df[df.columns[9]].value_counts()

('hypertension',
 array([0., 1.]),
 0.0    379
 1.0    238
 Name: hypertension, dtype: int64)

## 4. 'cholestrol'

In [29]:
df.columns[10]

'cholesterol'

In [30]:
df[df.columns[10]]

0      289.0
1      180.0
2      283.0
3      214.0
4        NaN
       ...  
612    333.0
613    139.0
614    223.0
615    385.0
616    254.0
Name: cholesterol, Length: 617, dtype: float64

In [31]:
df[df.columns[10]].fillna(df[df.columns[10]].mean() , inplace = True)

## 5. 'fasting blood sugar'

In [32]:
df.columns[11]

'fasting blood sugar'

In [33]:
df[df.columns[11]]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
612    1.0
613    0.0
614    1.0
615    1.0
616    0.0
Name: fasting blood sugar, Length: 617, dtype: float64

In [34]:
df[df.columns[11]].fillna(stats.mode(df[df.columns[11]]) , inplace = True)

In [35]:
df.columns[11] , df[df.columns[11]].unique() , df[df.columns[11]].value_counts()

('fasting blood sugar',
 array([0., 1.]),
 0.0    524
 1.0     93
 Name: fasting blood sugar, dtype: int64)

## 6. 'resting ecg'

In [36]:
df.columns[12]

'resting ecg'

In [37]:
df[df.columns[12]].unique()

array([ 0.,  1.,  2., nan])

In [38]:
df[df.columns[12]].fillna(stats.mode(df[df.columns[12]]) , inplace = True)

In [39]:
df[df.columns[12]].unique() , df[df.columns[12]].value_counts()

(array([0., 1., 2.]),
 0.0    402
 1.0    175
 2.0     40
 Name: resting ecg, dtype: int64)

## 7. 'digitalis'

In [40]:
df.columns[16]

'digitalis'

In [41]:
df[df.columns[16]].unique()

array([ 0., nan,  1.])

In [42]:
stats.mode(df['digitalis'])

0.0

In [43]:
df['digitalis'].fillna(stats.mode(df['digitalis']) , inplace = True)

## 8. 'beta blocker'

In [44]:
df.columns[17]

'beta blocker'

In [45]:
df[df.columns[17]].unique()

array([ 0.,  1., nan, 22.])

In [46]:
stats.mode(df[df.columns[17]])

0.0

In [47]:
df[df.columns[17]].fillna(stats.mode(df[df.columns[17]]) , inplace = True)

## 9. 'nitrates'

In [48]:
df.columns[18]

'nitrates'

In [49]:
df[df.columns[18]].value_counts()

0.0    401
1.0    153
Name: nitrates, dtype: int64

In [50]:
df[df.columns[18]].fillna(stats.mode(df[df.columns[18]]) , inplace = True)

## 10. 'calcium channel blocker'

In [51]:
df.columns[19]

'calcium channel blocker'

In [52]:
df[df.columns[19]].value_counts()

0.0    440
1.0    116
Name: calcium channel blocker, dtype: int64

In [53]:
df[df.columns[19]].fillna(stats.mode(df[df.columns[19]]) , inplace = True)

## 11. 'diuretic'

In [54]:
df.columns[20]

'diuretic'

In [55]:
df[df.columns[20]].value_counts()

0.0    477
1.0     60
Name: diuretic, dtype: int64

In [56]:
df[df.columns[20]].fillna(stats.mode(df[df.columns[20]]) , inplace = True)

## 12. 'exercise protocol'

In [57]:
df.columns[21]

'exercise protocol'

In [58]:
df[df.columns[21]].value_counts()

5.0      98
12.0     73
75.0     73
100.0    70
125.0    52
1.0      42
50.0     34
150.0    25
25.0     16
175.0    12
6.0       5
4.0       2
200.0     2
130.0     1
Name: exercise protocol, dtype: int64

In [59]:
df[df.columns[21]].fillna(stats.mean(df[df.columns[21]]) , inplace = True)

## 13. 'duration of exercise'

In [60]:
df.columns[22]

'duration of exercise'

In [61]:
df[df.columns[22]]

0      18.0
1      10.0
2      10.0
3       5.0
4       2.0
       ... 
612     7.5
613     NaN
614     5.3
615     NaN
616     6.7
Name: duration of exercise, Length: 617, dtype: float64

In [62]:
df[df.columns[22]].fillna(stats.mean(df[df.columns[22]]) , inplace = True)

## 14. 'mets achieved'

In [63]:
df.columns[23]

'mets achieved'

In [64]:
df[df.columns[23]]

0      7.0
1      7.0
2      5.0
3      4.0
4      3.0
      ... 
612    8.0
613    NaN
614    5.0
615    NaN
616    7.0
Name: mets achieved, Length: 617, dtype: float64

In [65]:
df[df.columns[23]].fillna(stats.mean(df[df.columns[23]]) , inplace = True)

## 15. 'max heart rate'

In [66]:
df.columns[24]

'max heart rate'

In [67]:
df[df.columns[24]]

0      172.0
1      156.0
2       98.0
3      108.0
4      122.0
       ...  
612    154.0
613      NaN
614    100.0
615      NaN
616     93.0
Name: max heart rate, Length: 617, dtype: float64

In [68]:
df[df.columns[24]].fillna(stats.mean(df[df.columns[24]]) , inplace = True)

## 16. 'resting heart rate'

In [69]:
df.columns[25]

'resting heart rate'

In [70]:
df[df.columns[25]]

0       86.0
1      100.0
2       58.0
3       54.0
4       74.0
       ...  
612     83.0
613      NaN
614     74.0
615      NaN
616     67.0
Name: resting heart rate, Length: 617, dtype: float64

In [71]:
df[df.columns[25]].fillna(stats.mean(df[df.columns[25]]) , inplace = True)

## 17. 'peak exercise bp 1'

In [72]:
df.columns[26]

'peak exercise bp 1'

In [73]:
df[df.columns[26]]

0      200.0
1      220.0
2      180.0
3      210.0
4      130.0
       ...  
612    158.0
613      NaN
614    210.0
615      NaN
616    164.0
Name: peak exercise bp 1, Length: 617, dtype: float64

In [74]:
df[df.columns[26]].fillna(stats.mean(df[df.columns[26]]) , inplace = True)

## 18. 'peak exercise bp 2'

In [75]:
df.columns[27]

'peak exercise bp 2'

In [76]:
df[df.columns[27]].fillna(stats.mean(df[df.columns[27]]) , inplace = True)

## 19. 'resting bp d'

In [77]:
df.columns[28]

'resting bp d'

In [78]:
df[df.columns[28]].fillna(stats.mean(df[df.columns[28]]) , inplace = True)

## 20. 'exercise angina'

In [79]:
df.columns[29]

'exercise angina'

In [80]:
df[df.columns[29]].value_counts()

0.0    324
1.0    238
Name: exercise angina, dtype: int64

In [81]:
df[df.columns[29]].fillna(stats.mode(df[df.columns[29]]) , inplace = True)

## 21. 'xhypo'

In [82]:
df.columns[30]

'xhypo'

In [83]:
df[df.columns[30]].value_counts()

0.0    543
1.0     16
Name: xhypo, dtype: int64

In [84]:
df[df.columns[30]].fillna(stats.mode(df[df.columns[30]]) , inplace = True)

## 22. 'oldpeak'

In [85]:
df.columns[31]

'oldpeak'

In [86]:
df[df.columns[31]]

0      0.0
1      1.0
2      0.0
3      1.5
4      0.0
      ... 
612    0.0
613    NaN
614    0.0
615    NaN
616    0.0
Name: oldpeak, Length: 617, dtype: float64

In [87]:
df[df.columns[31]].fillna(stats.mean(df[df.columns[31]]) , inplace = True)

## 23. 'ST height at rest'

In [88]:
df.columns[32]

'ST height at rest'

In [89]:
df[df.columns[32]]

0      26.0
1      14.0
2      17.0
3      19.0
4      13.0
       ... 
612    20.0
613     NaN
614     6.0
615     NaN
616    21.0
Name: ST height at rest, Length: 617, dtype: float64

In [90]:
df[df.columns[32]].fillna(stats.mean(df[df.columns[32]]) , inplace = True)

## 24. 'ST heaight at peak'

In [91]:
df.columns[33]

'ST heaight at peak'

In [92]:
df[df.columns[33]].fillna(stats.mean(df[df.columns[33]]) , inplace = True)

## 25. others

In [93]:
cols = [13,14,15,34,35,36]

In [94]:
df.drop(df.columns[cols] , axis = 1 , inplace = True)

In [95]:
df.columns

Index(['_id', 'ccf', 'age', 'sex', 'pain location', 'pain w exertion',
       'relieved after rest', 'chest pain type', 'resting bp s',
       'hypertension', 'cholesterol', 'fasting blood sugar', 'resting ecg',
       'digitalis', 'beta blocker', 'nitrates', 'calcium channel blocker',
       'diuretic', 'exercise protocol', 'duration of exercise',
       'mets achieved', 'max heart rate', 'resting heart rate',
       'peak exercise bp 1', 'peak exercise bp 2', 'resting bp d',
       'exercise angina', 'xhypo', 'oldpeak', 'ST height at rest',
       'ST heaight at peak', 'target'],
      dtype='object')

In [96]:
df.shape

(617, 32)

In [97]:
df.isnull().sum()

_id                          0
ccf                          0
age                          0
sex                          0
pain location                0
pain w exertion              0
relieved after rest          0
chest pain type              0
resting bp s                 0
hypertension                 0
cholesterol                  0
fasting blood sugar          0
resting ecg                  0
digitalis                    0
beta blocker                 0
nitrates                     0
calcium channel blocker      0
diuretic                     0
exercise protocol          112
duration of exercise        56
mets achieved              105
max heart rate              55
resting heart rate          56
peak exercise bp 1          63
peak exercise bp 2          63
resting bp d                59
exercise angina              0
xhypo                        0
oldpeak                     62
ST height at rest          143
ST heaight at peak         142
target                       0
dtype: i

In [98]:
cols = [18,19,20,21,22,23,24,25,28,29,30]

In [99]:
for i in cols:
    df.iloc[:,i].fillna(df.iloc[:,i].mean() , inplace = True)

In [100]:
df.isnull().sum()

_id                        0
ccf                        0
age                        0
sex                        0
pain location              0
pain w exertion            0
relieved after rest        0
chest pain type            0
resting bp s               0
hypertension               0
cholesterol                0
fasting blood sugar        0
resting ecg                0
digitalis                  0
beta blocker               0
nitrates                   0
calcium channel blocker    0
diuretic                   0
exercise protocol          0
duration of exercise       0
mets achieved              0
max heart rate             0
resting heart rate         0
peak exercise bp 1         0
peak exercise bp 2         0
resting bp d               0
exercise angina            0
xhypo                      0
oldpeak                    0
ST height at rest          0
ST heaight at peak         0
target                     0
dtype: int64

In [101]:
#df.to_csv('processedheartdata.csv', index = None)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617 entries, 0 to 616
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   _id                      617 non-null    int64  
 1   ccf                      617 non-null    int64  
 2   age                      617 non-null    int64  
 3   sex                      617 non-null    int64  
 4   pain location            617 non-null    int64  
 5   pain w exertion          617 non-null    int64  
 6   relieved after rest      617 non-null    float64
 7   chest pain type          617 non-null    int64  
 8   resting bp s             617 non-null    float64
 9   hypertension             617 non-null    float64
 10  cholesterol              617 non-null    float64
 11  fasting blood sugar      617 non-null    float64
 12  resting ecg              617 non-null    float64
 13  digitalis                617 non-null    float64
 14  beta blocker             6